title: Gokul Nishanth Sivakumar # your name (or website title) here
logo: "/images/IMG_0889.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Aspiring Data Scientist with experience in Data Analysis, Machine Learning, Predictive modeling, Big Data Mining, 
  Recommender Systems, and Computer Vision. 
  <br>
  Graduate Reasearch Assistant at DePaul Univeristy working on a project in collaboration with Northwestern Memorial Hospital, 
  to develop a classification model that is intelligent to prognosticate Age-Related Macular Degeneration disease, a leading cause of 
  irreversible vision loss in elders, using image processing and deep learning.
  <br>
  <a href="https://www.linkedin.com/in/gokulsivakumar/">View My LinkedIn Profile</a> 

theme: jekyll-theme-minimal
google_analytics: G-Y9XERNPKRP # your Google Analytics tracking ID here
