title: Gokul Nishanth Sivakumar # your name (or website title) here
logo: "/images/IMG_0889.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/gokulsivakumar/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-Y9XERNPKRP # your Google Analytics tracking ID here
