title: Gokul Nishanth Sivakumar # your name (or website title) here
logo: "/images/IMG_0889.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Aspiring Data Scientist with experience in Data Analysis, Machine Learning, Neural networks, predictive modeling, big data mining, recommender systems, and computer vision. 
  <br>
  Skills:
  Programming Languages: Python, PL/SQL, R, C, C++, Java
  Tools: Jupyter, Pycharm, Visual Studio Code
  Technologies: TensorFlow, Keras, OpenCV, Pandas, NumPy, SciPy, scikit-learn, Matplotlib, NLTK
  Big Data Mining: Hadoop, SQL, Hive, Spark
  Visualization: Tableau, Matplotlib, ggplot, seaborn
  Cloud: AWS, Google Cloud 
  <br><br>
  <a href="https://www.linkedin.com/in/gokulsivakumar/">View My LinkedIn Profile</a> 
  
 --
theme: jekyll-theme-minimal
google_analytics: G-Y9XERNPKRP # your Google Analytics tracking ID here
